image: nodejs

before_script:
  - npm -g install eslint --silent
  - npm set progress=false
  - npm install --silent
stages:
  - test
  - build
  - clean_up

run_tests:
  stage: test
  script:
    - npm run lint

build_and_deploy_prod:
  stage: build
  script:
    - npm run build
  only:
    - master

clean_up_job:
  stage: clean_up
  script:
    - npm run clean
  when: on_failure